#!/bin/bash

################################################################################
# PRE-OPTIMIZATION BASELINE CHECK SCRIPT
#
# Purpose: Capture complete system state BEFORE applying optimizations
# Server: CEPCOMUNICACION-PROD (Hetzner VPS - 46.62.222.138)
# Date: 2025-11-03
# Author: SOLARIA AGENCY
#
# This script must be run as ROOT before optimization
################################################################################

set -euo pipefail

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Output directory
BASELINE_DIR="/root/server-optimization/baseline"
BACKUP_DIR="/root/server-optimization/config-backups"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REPORT_FILE="${BASELINE_DIR}/baseline-report-${TIMESTAMP}.txt"

################################################################################
# Helper Functions
################################################################################

print_header() {
    echo -e "\n${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}\n"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

log_section() {
    echo "" >> "$REPORT_FILE"
    echo "========================================" >> "$REPORT_FILE"
    echo "$1" >> "$REPORT_FILE"
    echo "========================================" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
}

################################################################################
# Pre-flight Checks
################################################################################

preflight_checks() {
    print_header "PRE-FLIGHT CHECKS"

    # Check if running as root
    if [[ $EUID -ne 0 ]]; then
        print_error "This script must be run as root"
        exit 1
    fi
    print_success "Running as root"

    # Create directories
    mkdir -p "$BASELINE_DIR"
    mkdir -p "$BACKUP_DIR"
    print_success "Created output directories"

    # Check required commands
    local required_commands=("sysctl" "free" "df" "lscpu" "iostat" "netstat" "ss")
    for cmd in "${required_commands[@]}"; do
        if ! command -v "$cmd" &> /dev/null; then
            print_warning "Command '$cmd' not found - installing sysstat package"
            apt-get update -qq
            apt-get install -y sysstat net-tools &> /dev/null
        fi
    done
    print_success "All required commands available"

    # Initialize report file
    cat > "$REPORT_FILE" <<EOF
################################################################################
# SERVER OPTIMIZATION - BASELINE REPORT
################################################################################

Server: CEPCOMUNICACION-PROD
IP: 46.62.222.138
Provider: Hetzner
Timestamp: $(date '+%Y-%m-%d %H:%M:%S %Z')
Generated by: pre-optimization-check.sh

This report captures the BASELINE state of the server BEFORE optimization.
Use this as reference for comparison after optimization.

EOF
    print_success "Initialized report file: $REPORT_FILE"
}

################################################################################
# System Information
################################################################################

collect_system_info() {
    print_header "COLLECTING SYSTEM INFORMATION"
    log_section "SYSTEM INFORMATION"

    # Hostname and kernel
    print_info "Capturing hostname and kernel info"
    {
        echo "Hostname: $(hostname)"
        echo "Kernel: $(uname -r)"
        echo "OS: $(lsb_release -d | cut -f2)"
        echo "Architecture: $(uname -m)"
        echo "Uptime: $(uptime -p)"
        echo "Boot Time: $(who -b | awk '{print $3, $4}')"
    } >> "$REPORT_FILE"
    print_success "System information collected"

    # CPU information
    print_info "Capturing CPU information"
    log_section "CPU INFORMATION"
    {
        lscpu
        echo ""
        echo "CPU Model:"
        grep "model name" /proc/cpuinfo | head -1
        echo ""
        echo "CPU Count:"
        nproc
    } >> "$REPORT_FILE"
    print_success "CPU information collected"

    # Memory information
    print_info "Capturing memory information"
    log_section "MEMORY INFORMATION"
    {
        free -h
        echo ""
        echo "Memory Details:"
        cat /proc/meminfo | grep -E "^(MemTotal|MemFree|MemAvailable|Buffers|Cached|SwapTotal|SwapFree)"
    } >> "$REPORT_FILE"
    print_success "Memory information collected"

    # Disk information
    print_info "Capturing disk information"
    log_section "DISK INFORMATION"
    {
        df -h
        echo ""
        echo "Disk Details:"
        lsblk
        echo ""
        echo "Mount Options:"
        cat /proc/mounts
    } >> "$REPORT_FILE"
    print_success "Disk information collected"
}

################################################################################
# Swap Configuration
################################################################################

collect_swap_info() {
    print_header "COLLECTING SWAP CONFIGURATION"
    log_section "SWAP CONFIGURATION"

    print_info "Checking swap status"
    {
        echo "Swap Status:"
        swapon --show 2>&1 || echo "No swap configured"
        echo ""
        echo "Swap Statistics:"
        cat /proc/swaps
        echo ""
        echo "VM Swappiness:"
        sysctl vm.swappiness
        echo ""
        echo "VM Cache Pressure:"
        sysctl vm.vfs_cache_pressure
    } >> "$REPORT_FILE"

    if [[ $(swapon --show | wc -l) -eq 0 ]]; then
        print_warning "No swap configured - CRITICAL RISK for production"
    else
        print_success "Swap configuration captured"
    fi
}

################################################################################
# Kernel Parameters (sysctl)
################################################################################

collect_kernel_parameters() {
    print_header "COLLECTING KERNEL PARAMETERS"
    log_section "KERNEL PARAMETERS (SYSCTL)"

    print_info "Capturing all sysctl parameters"
    sysctl -a 2>/dev/null >> "$REPORT_FILE"
    print_success "Kernel parameters collected"

    # Highlight important parameters
    log_section "KEY KERNEL PARAMETERS"
    {
        echo "Network Parameters:"
        sysctl net.core.somaxconn
        sysctl net.core.netdev_max_backlog
        sysctl net.ipv4.tcp_max_syn_backlog
        sysctl net.ipv4.tcp_fin_timeout
        sysctl net.ipv4.tcp_tw_reuse
        sysctl net.ipv4.ip_local_port_range
        echo ""
        echo "Memory Parameters:"
        sysctl vm.swappiness
        sysctl vm.vfs_cache_pressure
        sysctl vm.dirty_ratio
        sysctl vm.dirty_background_ratio
        sysctl vm.overcommit_memory
        echo ""
        echo "File System Parameters:"
        sysctl fs.file-max
        sysctl fs.inode-max 2>/dev/null || echo "fs.inode-max: not set"
    } >> "$REPORT_FILE"
    print_success "Key parameters highlighted"
}

################################################################################
# File Descriptor Limits
################################################################################

collect_fd_limits() {
    print_header "COLLECTING FILE DESCRIPTOR LIMITS"
    log_section "FILE DESCRIPTOR LIMITS"

    print_info "Capturing ulimit settings"
    {
        echo "Current Shell Limits:"
        ulimit -a
        echo ""
        echo "System-wide Limits (/etc/security/limits.conf):"
        cat /etc/security/limits.conf | grep -v "^#" | grep -v "^$"
        echo ""
        echo "File Descriptor Statistics:"
        echo "Open files: $(lsof 2>/dev/null | wc -l)"
        echo "Max files: $(sysctl -n fs.file-max)"
    } >> "$REPORT_FILE"
    print_success "File descriptor limits collected"
}

################################################################################
# Network Configuration
################################################################################

collect_network_info() {
    print_header "COLLECTING NETWORK CONFIGURATION"
    log_section "NETWORK CONFIGURATION"

    print_info "Capturing network interfaces"
    {
        echo "Network Interfaces:"
        ip addr
        echo ""
        echo "Routing Table:"
        ip route
        echo ""
        echo "TCP Congestion Control:"
        sysctl net.ipv4.tcp_congestion_control
        echo ""
        echo "Connection Statistics:"
        ss -s
    } >> "$REPORT_FILE"
    print_success "Network configuration collected"
}

################################################################################
# I/O Scheduler and Disk Performance
################################################################################

collect_disk_performance() {
    print_header "COLLECTING DISK I/O CONFIGURATION"
    log_section "DISK I/O CONFIGURATION"

    print_info "Capturing I/O scheduler settings"
    {
        echo "I/O Schedulers by Device:"
        for disk in /sys/block/sd*/queue/scheduler; do
            echo "$disk: $(cat $disk)"
        done
        echo ""
        echo "Read-ahead Settings:"
        for disk in /sys/block/sd*/queue/read_ahead_kb; do
            echo "$disk: $(cat $disk) KB"
        done
        echo ""
        echo "I/O Statistics (5 samples):"
        iostat -x 1 5
    } >> "$REPORT_FILE"
    print_success "Disk I/O configuration collected"
}

################################################################################
# systemd Configuration
################################################################################

collect_systemd_config() {
    print_header "COLLECTING SYSTEMD CONFIGURATION"
    log_section "SYSTEMD CONFIGURATION"

    print_info "Capturing systemd limits"
    {
        echo "System-wide Service Limits:"
        grep -E "^Default" /etc/systemd/system.conf 2>/dev/null || echo "Using defaults"
        echo ""
        echo "User Service Limits:"
        grep -E "^Default" /etc/systemd/user.conf 2>/dev/null || echo "Using defaults"
    } >> "$REPORT_FILE"
    print_success "systemd configuration collected"
}

################################################################################
# Running Services
################################################################################

collect_running_services() {
    print_header "COLLECTING RUNNING SERVICES"
    log_section "RUNNING SERVICES"

    print_info "Listing active services"
    {
        echo "Active Services:"
        systemctl list-units --type=service --state=running --no-pager
        echo ""
        echo "Enabled Services:"
        systemctl list-unit-files --type=service --state=enabled --no-pager
    } >> "$REPORT_FILE"
    print_success "Running services collected"
}

################################################################################
# Current Resource Usage
################################################################################

collect_resource_usage() {
    print_header "COLLECTING RESOURCE USAGE"
    log_section "CURRENT RESOURCE USAGE"

    print_info "Capturing current resource consumption"
    {
        echo "Memory Usage:"
        free -h
        echo ""
        echo "Top 10 Memory Consumers:"
        ps aux --sort=-%mem | head -11
        echo ""
        echo "Top 10 CPU Consumers:"
        ps aux --sort=-%cpu | head -11
        echo ""
        echo "Load Average:"
        uptime
    } >> "$REPORT_FILE"
    print_success "Resource usage collected"
}

################################################################################
# Backup Configuration Files
################################################################################

backup_config_files() {
    print_header "BACKING UP CONFIGURATION FILES"

    local config_files=(
        "/etc/sysctl.conf"
        "/etc/security/limits.conf"
        "/etc/systemd/system.conf"
        "/etc/systemd/user.conf"
        "/etc/fstab"
        "/etc/systemd/journald.conf"
    )

    for file in "${config_files[@]}"; do
        if [[ -f "$file" ]]; then
            print_info "Backing up: $file"
            cp -p "$file" "${BACKUP_DIR}/$(basename $file).${TIMESTAMP}.bak"
            print_success "Backed up: $file"
        else
            print_warning "File not found: $file"
        fi
    done

    # Backup entire sysctl values
    print_info "Backing up all sysctl values"
    sysctl -a 2>/dev/null > "${BACKUP_DIR}/sysctl-all.${TIMESTAMP}.bak"
    print_success "All sysctl values backed up"
}

################################################################################
# Timezone Check
################################################################################

collect_timezone_info() {
    print_header "COLLECTING TIMEZONE INFORMATION"
    log_section "TIMEZONE CONFIGURATION"

    {
        echo "Current Timezone:"
        timedatectl
        echo ""
        echo "Time Synchronization:"
        systemctl status systemd-timesyncd --no-pager 2>&1 || echo "systemd-timesyncd not active"
    } >> "$REPORT_FILE"
    print_success "Timezone information collected"
}

################################################################################
# Generate Summary
################################################################################

generate_summary() {
    print_header "GENERATING SUMMARY"
    log_section "OPTIMIZATION RECOMMENDATIONS"

    local recommendations=()

    # Check swap
    if [[ $(swapon --show | wc -l) -eq 0 ]]; then
        recommendations+=("CRITICAL: No swap configured - add 4GB swap file")
    fi

    # Check swappiness
    local swappiness=$(sysctl -n vm.swappiness)
    if [[ $swappiness -gt 10 ]]; then
        recommendations+=("Reduce vm.swappiness from $swappiness to 10")
    fi

    # Check file descriptor limit
    local file_max=$(sysctl -n fs.file-max)
    if [[ $file_max -lt 65536 ]]; then
        recommendations+=("Increase fs.file-max from $file_max to 2097152")
    fi

    # Check somaxconn
    local somaxconn=$(sysctl -n net.core.somaxconn)
    if [[ $somaxconn -lt 4096 ]]; then
        recommendations+=("Increase net.core.somaxconn from $somaxconn to 4096")
    fi

    # Output recommendations
    {
        echo "CRITICAL OPTIMIZATIONS NEEDED:"
        echo ""
        for i in "${!recommendations[@]}"; do
            echo "$((i+1)). ${recommendations[$i]}"
        done
        echo ""
        echo "Total recommendations: ${#recommendations[@]}"
    } >> "$REPORT_FILE"

    print_success "Summary generated with ${#recommendations[@]} recommendations"
}

################################################################################
# Main Execution
################################################################################

main() {
    echo ""
    echo "╔════════════════════════════════════════════════════════════════╗"
    echo "║   SERVER OPTIMIZATION - BASELINE CHECK                         ║"
    echo "║   CEPCOMUNICACION-PROD (Hetzner VPS)                          ║"
    echo "╚════════════════════════════════════════════════════════════════╝"
    echo ""

    preflight_checks
    collect_system_info
    collect_swap_info
    collect_kernel_parameters
    collect_fd_limits
    collect_network_info
    collect_disk_performance
    collect_systemd_config
    collect_running_services
    collect_resource_usage
    collect_timezone_info
    backup_config_files
    generate_summary

    print_header "BASELINE CHECK COMPLETE"
    print_success "Report saved: $REPORT_FILE"
    print_success "Backups saved: $BACKUP_DIR"

    echo ""
    echo "Next steps:"
    echo "1. Review the baseline report: cat $REPORT_FILE"
    echo "2. Run optimization script: ./optimize-server.sh"
    echo "3. Reboot the server: reboot"
    echo "4. Run post-optimization check: ./post-optimization-check.sh"
    echo ""
}

# Execute main function
main "$@"
