import { TeacherExpanded } from '@/types'

export const teachersExpanded: TeacherExpanded[] = [
  {
    id: '1',
    first_name: 'María',
    last_name: 'García Pérez',
    initials: 'MG',
    email: 'maria.garcia@cepcomunicacion.com',
    phone: '+34 612 345 678',
    photo: 'https://i.pravatar.cc/150?img=1',
    department: 'Marketing Digital',
    specialties: ['SEO', 'SEM', 'Analytics', 'Google Ads', 'Meta Ads'],
    bio: '15 años de experiencia en marketing digital y publicidad. Especializada en campañas de rendimiento para e-commerce y generación de leads B2B. Ha gestionado presupuestos superiores a 500K€ anuales con ROI promedio del 320%.',
    active: true,
    courses_count: 3,
    certifications: [
      {
        title: 'Google Ads Certified',
        institution: 'Google',
        year: 2023,
      },
      {
        title: 'Master en Marketing Digital',
        institution: 'ESIC Business School',
        year: 2019,
      },
      {
        title: 'Certificación Meta Blueprint',
        institution: 'Meta',
        year: 2022,
      },
    ],
    courses: [
      {
        id: 'CURSO001',
        name: 'Community Manager Profesional',
        code: 'CM-PRO-2025',
        type: 'Privado',
        modality: 'Semipresencial',
        students: 18,
      },
      {
        id: 'CURSO002',
        name: 'SEO y SEM Avanzado',
        code: 'SEO-SEM-ADV',
        type: 'Privado',
        modality: 'Presencial',
        students: 15,
      },
      {
        id: 'CURSO008',
        name: 'Marketing para Desempleados',
        code: 'MKT-DESEMP',
        type: 'Desempleados',
        modality: 'Semipresencial',
        students: 20,
      },
    ],
    campuses: ['C001', 'C002'],
  },
  {
    id: '2',
    first_name: 'Carlos',
    last_name: 'Rodríguez Martínez',
    initials: 'CR',
    email: 'carlos.rodriguez@cepcomunicacion.com',
    phone: '+34 612 345 679',
    photo: 'https://i.pravatar.cc/150?img=12',
    department: 'Desarrollo Web',
    specialties: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'Docker'],
    bio: 'Desarrollador full-stack con 10 años de experiencia en tecnologías web modernas. Ha liderado proyectos para empresas como CaixaBank y Telefónica. Especializado en arquitecturas escalables y metodologías ágiles.',
    active: true,
    courses_count: 2,
    certifications: [
      {
        title: 'AWS Certified Solutions Architect',
        institution: 'Amazon Web Services',
        year: 2023,
      },
      {
        title: 'Técnico Superior en Desarrollo de Aplicaciones Web',
        institution: 'CEP Comunicación',
        year: 2015,
      },
    ],
    courses: [
      {
        id: 'CURSO004',
        name: 'Desarrollo Frontend con React',
        code: 'REACT-2025',
        type: 'Ciclo Superior',
        modality: 'Presencial',
        students: 12,
      },
      {
        id: 'CURSO005',
        name: 'Backend con Node.js y PostgreSQL',
        code: 'NODE-PSQL',
        type: 'Ciclo Superior',
        modality: 'Semipresencial',
        students: 9,
      },
    ],
    campuses: ['C001'],
  },
  {
    id: '3',
    first_name: 'Laura',
    last_name: 'Martínez Sosa',
    initials: 'LM',
    email: 'laura.martinez@cepcomunicacion.com',
    phone: '+34 634 567 890',
    photo: 'https://i.pravatar.cc/150?img=5',
    department: 'Diseño Gráfico',
    specialties: ['Figma', 'Adobe XD', 'UI/UX', 'Design Systems', 'Prototipado'],
    bio: 'Diseñadora UX/UI con 12 años de experiencia en diseño centrado en el usuario. Ha trabajado para startups como Glovo y Cabify. Especialista en design systems y metodologías de diseño ágil.',
    active: true,
    courses_count: 2,
    certifications: [
      {
        title: 'UX Design Professional Certificate',
        institution: 'Google',
        year: 2022,
      },
      {
        title: 'Advanced Figma Certification',
        institution: 'Figma',
        year: 2023,
      },
    ],
    courses: [
      {
        id: 'CURSO003',
        name: 'Diseño UX/UI con Figma',
        code: 'UX-UI-FIG',
        type: 'Privado',
        modality: 'Semipresencial',
        students: 14,
      },
      {
        id: 'CURSO006',
        name: 'Design Systems Profesional',
        code: 'DS-PRO',
        type: 'Privado',
        modality: 'Presencial',
        students: 10,
      },
    ],
    campuses: ['C001', 'C002'],
  },
  {
    id: '4',
    first_name: 'Javier',
    last_name: 'Fernández Ruiz',
    initials: 'JF',
    email: 'javier.fernandez@cepcomunicacion.com',
    phone: '+34 645 678 901',
    photo: 'https://i.pravatar.cc/150?img=15',
    department: 'Audiovisual',
    specialties: ['Premiere Pro', 'After Effects', 'DaVinci Resolve', 'Producción', 'Motion Graphics'],
    bio: 'Productor audiovisual y editor con más de 8 años en televisión y publicidad. Ha trabajado en producciones para Antena 3 y Mediaset. Especializado en postproducción y motion graphics.',
    active: true,
    courses_count: 2,
    certifications: [
      {
        title: 'Adobe Certified Expert - Premiere Pro',
        institution: 'Adobe',
        year: 2021,
      },
      {
        title: 'DaVinci Resolve Colorist Certification',
        institution: 'Blackmagic Design',
        year: 2023,
      },
    ],
    courses: [
      {
        id: 'CURSO007',
        name: 'Edición de Vídeo Profesional',
        code: 'VIDEO-PRO',
        type: 'Privado',
        modality: 'Presencial',
        students: 11,
      },
      {
        id: 'CURSO009',
        name: 'Motion Graphics y VFX',
        code: 'MOTION-VFX',
        type: 'Ciclo Superior',
        modality: 'Presencial',
        students: 13,
      },
    ],
    campuses: ['C001', 'C003'],
  },
  {
    id: '5',
    first_name: 'Ana',
    last_name: 'López Torres',
    initials: 'AL',
    email: 'ana.lopez@cepcomunicacion.com',
    phone: '+34 656 789 012',
    photo: 'https://i.pravatar.cc/150?img=9',
    department: 'Marketing Digital',
    specialties: ['Instagram', 'TikTok', 'Content Marketing', 'Copywriting', 'Influencer Marketing'],
    bio: 'Community Manager y Content Creator con 7 años de experiencia gestionando cuentas de más de 500K seguidores. Especializada en estrategias de contenido viral y growth hacking en redes sociales.',
    active: true,
    courses_count: 3,
    certifications: [
      {
        title: 'Meta Social Media Marketing Professional Certificate',
        institution: 'Meta',
        year: 2022,
      },
      {
        title: 'Content Marketing Certified',
        institution: 'HubSpot Academy',
        year: 2023,
      },
    ],
    courses: [
      {
        id: 'CURSO010',
        name: 'TikTok y Reels para Empresas',
        code: 'TIKTOK-BIZ',
        type: 'Privado',
        modality: 'Telemático',
        students: 22,
      },
      {
        id: 'CURSO011',
        name: 'Content Marketing Estratégico',
        code: 'CONTENT-STR',
        type: 'Ocupados',
        modality: 'Semipresencial',
        students: 17,
      },
      {
        id: 'CURSO001',
        name: 'Community Manager Profesional',
        code: 'CM-PRO-2025',
        type: 'Privado',
        modality: 'Semipresencial',
        students: 18,
      },
    ],
    campuses: ['C002', 'C004'],
  },
  {
    id: '6',
    first_name: 'Elena',
    last_name: 'Sánchez Mora',
    initials: 'ES',
    email: 'elena.sanchez@cepcomunicacion.com',
    phone: '+34 667 890 123',
    photo: 'https://i.pravatar.cc/150?img=20',
    department: 'Gestión Empresarial',
    specialties: ['Excel Avanzado', 'Power BI', 'Business Intelligence', 'Project Management', 'Lean Six Sigma'],
    bio: 'Consultora de gestión y analista de negocio con MBA. 13 años de experiencia en análisis de datos y mejora de procesos empresariales. Certificada en Project Management Professional (PMP) y Lean Six Sigma Black Belt.',
    active: true,
    courses_count: 2,
    certifications: [
      {
        title: 'Project Management Professional (PMP)',
        institution: 'PMI',
        year: 2020,
      },
      {
        title: 'Lean Six Sigma Black Belt',
        institution: 'ASQ',
        year: 2021,
      },
      {
        title: 'MBA',
        institution: 'IESE Business School',
        year: 2016,
      },
    ],
    courses: [
      {
        id: 'CURSO012',
        name: 'Excel Avanzado y Power BI',
        code: 'EXCEL-BI',
        type: 'Ocupados',
        modality: 'Telemático',
        students: 32,
      },
      {
        id: 'CURSO013',
        name: 'Gestión de Proyectos Ágil',
        code: 'PM-AGILE',
        type: 'Privado',
        modality: 'Presencial',
        students: 16,
      },
    ],
    campuses: ['C001', 'C002', 'C004'],
  },
]
