import { DashboardMetrics, Convocation, Campaign } from '@/types'

export const dashboardMetrics: DashboardMetrics = {
  total_courses: 45,
  active_courses: 28,
  total_students: 892,
  active_students: 674,
  total_leads: 1248,
  leads_this_month: 187,
  conversion_rate: 32.5,
  total_revenue: 245680,
  active_convocations: 12,
  total_teachers: 24,
  total_campuses: 3,
  classroom_utilization: 76,
}

export const convocations: Convocation[] = [
  {
    id: '1',
    course_id: 'c1',
    course_title: 'Marketing Digital Avanzado',
    start_date: '2025-02-01',
    end_date: '2025-06-30',
    status: 'abierta',
    capacity_min: 12,
    capacity_max: 25,
    enrolled: 18,
    campus_id: 's1',
    campus_name: 'CEP Norte',
    price: 890,
  },
  {
    id: '2',
    course_id: 'c2',
    course_title: 'Desarrollo Web Full Stack',
    start_date: '2025-02-15',
    end_date: '2025-07-15',
    status: 'abierta',
    capacity_min: 10,
    capacity_max: 20,
    enrolled: 15,
    campus_id: 's2',
    campus_name: 'CEP Santa Cruz',
    price: 1200,
  },
  {
    id: '3',
    course_id: 'c3',
    course_title: 'Diseño Gráfico Profesional',
    start_date: '2025-03-01',
    end_date: '2025-06-15',
    status: 'planificada',
    capacity_min: 8,
    capacity_max: 15,
    enrolled: 0,
    campus_id: 's3',
    campus_name: 'CEP Sur',
    price: 780,
  },
  {
    id: '4',
    course_id: 'c4',
    course_title: 'Gestión de Redes Sociales',
    start_date: '2025-01-20',
    end_date: '2025-05-20',
    status: 'lista_espera',
    capacity_min: 15,
    capacity_max: 25,
    enrolled: 25,
    campus_id: 's1',
    campus_name: 'CEP Norte',
    price: 650,
  },
  {
    id: '5',
    course_id: 'c5',
    course_title: 'Comercio Electrónico',
    start_date: '2025-02-10',
    end_date: '2025-06-10',
    status: 'abierta',
    capacity_min: 10,
    capacity_max: 18,
    enrolled: 12,
    campus_id: 's2',
    campus_name: 'CEP Santa Cruz',
    price: 720,
  },
]

export const campaigns: Campaign[] = [
  {
    id: '1',
    name: 'Campaña Marketing Digital Q1 2025',
    description: 'Captación para cursos de marketing digital',
    status: 'activa',
    budget: 5000,
    leads_generated: 124,
    conversions: 42,
    conversion_rate: 33.9,
    cost_per_lead: 40.32,
    start_date: '2025-01-01',
    end_date: '2025-03-31',
  },
  {
    id: '2',
    name: 'Campaña Desarrollo Web',
    description: 'Promoción de cursos de programación',
    status: 'activa',
    budget: 3500,
    leads_generated: 89,
    conversions: 28,
    conversion_rate: 31.5,
    cost_per_lead: 39.33,
    start_date: '2025-01-15',
    end_date: '2025-04-15',
  },
  {
    id: '3',
    name: 'Diseño Gráfico - Promoción',
    description: 'Captación para cursos creativos',
    status: 'pausada',
    budget: 2000,
    leads_generated: 45,
    conversions: 12,
    conversion_rate: 26.7,
    cost_per_lead: 44.44,
    start_date: '2025-01-10',
    end_date: '2025-03-10',
  },
  {
    id: '4',
    name: 'Redes Sociales - Meta Ads',
    description: 'Campaña en Facebook e Instagram',
    status: 'activa',
    budget: 4200,
    leads_generated: 156,
    conversions: 51,
    conversion_rate: 32.7,
    cost_per_lead: 26.92,
    start_date: '2024-12-01',
    end_date: '2025-02-28',
  },
  {
    id: '5',
    name: 'E-commerce Navidad',
    description: 'Promoción especial fin de año',
    status: 'finalizada',
    budget: 3000,
    leads_generated: 98,
    conversions: 34,
    conversion_rate: 34.7,
    cost_per_lead: 30.61,
    start_date: '2024-11-15',
    end_date: '2024-12-31',
  },
]
