import { InstanciaVistaCompleta } from '@/types'

// Mock data for course instances
export const instanciasData: InstanciaVistaCompleta[] = [
  {
    id: '1',
    plantillaId: 'curso-1',
    nombreCurso: 'Marketing Digital Avanzado',
    descripcionCurso:
      'Domina estrategias avanzadas de marketing digital, SEO, SEM, y análisis de métricas para impulsar tu negocio.',
    imagenPortada: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=400&fit=crop',
    codigoCompleto: 'MARK-DIG-2025-01',
    tipo: 'privados',
    modalidad: 'semipresencial',
    estado: 'abierta',
    fechaInicio: '2025-02-15',
    fechaFin: '2025-06-30',
    horario: 'Lunes a Viernes 18:00-21:00',
    duracionHoras: 200,
    precio: 1200,
    plazasTotales: 25,
    plazasOcupadas: 18,
    porcentajeOcupacion: 72,
    profesorId: 'prof-1',
    profesorNombre: 'Ana García Martínez',
    profesorAvatar: undefined,
    sedeId: 'sede-norte',
    sedeNombre: 'CEP Norte',
    aulaId: 'aula-101',
    aulaNombre: 'Aula 101',
    subvencionado: 'no',
    entidadesFinanciadoras: [],
  },
  {
    id: '2',
    plantillaId: 'curso-2',
    nombreCurso: 'Desarrollo Web Full Stack',
    descripcionCurso:
      'Aprende a crear aplicaciones web completas desde el frontend hasta el backend con tecnologías modernas.',
    imagenPortada: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=400&fit=crop',
    codigoCompleto: 'DEV-WEB-2025-02',
    tipo: 'ocupados',
    modalidad: 'presencial',
    estado: 'abierta',
    fechaInicio: '2025-03-01',
    fechaFin: '2025-07-15',
    horario: 'Lunes a Jueves 16:00-20:00',
    duracionHoras: 300,
    precio: 0,
    plazasTotales: 20,
    plazasOcupadas: 15,
    porcentajeOcupacion: 75,
    profesorId: 'prof-2',
    profesorNombre: 'Carlos Rodríguez López',
    profesorAvatar: undefined,
    sedeId: 'sede-santa-cruz',
    sedeNombre: 'CEP Santa Cruz',
    aulaId: 'aula-201',
    aulaNombre: 'Aula 201',
    subvencionado: 'total',
    entidadesFinanciadoras: [
      {
        id: 'fundae',
        nombre: 'FUNDAE',
        logo: '/logos/fundae.png',
      },
    ],
  },
  {
    id: '3',
    plantillaId: 'curso-3',
    nombreCurso: 'Diseño Gráfico Profesional',
    descripcionCurso:
      'Herramientas y técnicas de diseño gráfico profesional con Adobe Creative Suite y Figma.',
    imagenPortada: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=400&fit=crop',
    codigoCompleto: 'DIS-GRAF-2025-01',
    tipo: 'desempleados',
    modalidad: 'presencial',
    estado: 'planificada',
    fechaInicio: '2025-03-15',
    fechaFin: '2025-06-30',
    horario: 'Lunes a Viernes 09:00-13:00',
    duracionHoras: 250,
    precio: 0,
    plazasTotales: 18,
    plazasOcupadas: 0,
    porcentajeOcupacion: 0,
    profesorId: 'prof-3',
    profesorNombre: 'Laura Fernández Soto',
    profesorAvatar: undefined,
    sedeId: 'sede-sur',
    sedeNombre: 'CEP Sur',
    aulaId: 'aula-302',
    aulaNombre: 'Aula 302',
    subvencionado: 'total',
    entidadesFinanciadoras: [
      {
        id: 'sepe',
        nombre: 'SEPE',
        logo: '/logos/sepe.png',
      },
    ],
  },
  {
    id: '4',
    plantillaId: 'curso-4',
    nombreCurso: 'Community Manager Profesional',
    descripcionCurso:
      'Gestión profesional de redes sociales, creación de contenido y análisis de métricas.',
    imagenPortada: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=400&fit=crop',
    codigoCompleto: 'CM-PRO-2025-01',
    tipo: 'teleformacion',
    modalidad: 'telematico',
    estado: 'abierta',
    fechaInicio: '2025-02-01',
    fechaFin: '2025-05-30',
    horario: '100% Online - Campus Virtual',
    duracionHoras: 150,
    precio: 800,
    plazasTotales: 30,
    plazasOcupadas: 25,
    porcentajeOcupacion: 83,
    profesorId: 'prof-4',
    profesorNombre: 'Miguel Sánchez Torres',
    profesorAvatar: undefined,
    sedeId: 'sede-online',
    sedeNombre: 'Campus Virtual',
    aulaId: 'aula-virtual',
    aulaNombre: 'Aula Virtual',
    subvencionado: 'no',
    entidadesFinanciadoras: [],
  },
  {
    id: '5',
    plantillaId: 'curso-5',
    nombreCurso: 'Producción Audiovisual',
    descripcionCurso:
      'Técnicas de producción, edición y postproducción de contenido audiovisual profesional.',
    imagenPortada: 'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?w=800&h=400&fit=crop',
    codigoCompleto: 'PROD-AV-2025-01',
    tipo: 'privados',
    modalidad: 'presencial',
    estado: 'lista_espera',
    fechaInicio: '2025-02-10',
    fechaFin: '2025-06-20',
    horario: 'Martes y Jueves 17:00-21:00',
    duracionHoras: 180,
    precio: 1500,
    precioConDescuento: 1200,
    plazasTotales: 15,
    plazasOcupadas: 15,
    porcentajeOcupacion: 100,
    profesorId: 'prof-5',
    profesorNombre: 'Elena Martín Ruiz',
    profesorAvatar: undefined,
    sedeId: 'sede-norte',
    sedeNombre: 'CEP Norte',
    aulaId: 'aula-lab',
    aulaNombre: 'Laboratorio de Medios',
    subvencionado: 'no',
    entidadesFinanciadoras: [],
  },
  {
    id: '6',
    plantillaId: 'curso-6',
    nombreCurso: 'Excel Avanzado y Business Intelligence',
    descripcionCurso: 'Domina Excel avanzado, Power BI y análisis de datos empresariales.',
    codigoCompleto: 'EXCEL-BI-2025-01',
    tipo: 'ocupados',
    modalidad: 'telematico',
    estado: 'abierta',
    fechaInicio: '2025-02-20',
    fechaFin: '2025-04-30',
    horario: '100% Online - Horario Flexible',
    duracionHoras: 120,
    precio: 0,
    plazasTotales: 40,
    plazasOcupadas: 32,
    porcentajeOcupacion: 80,
    profesorId: 'prof-6',
    profesorNombre: 'David González Pérez',
    profesorAvatar: undefined,
    sedeId: 'sede-online',
    sedeNombre: 'Campus Virtual',
    aulaId: 'aula-virtual-2',
    aulaNombre: 'Aula Virtual 2',
    subvencionado: 'total',
    entidadesFinanciadoras: [
      {
        id: 'fundae',
        nombre: 'FUNDAE',
        logo: '/logos/fundae.png',
      },
    ],
  },
  {
    id: '7',
    plantillaId: 'curso-7',
    nombreCurso: 'Fotografía Digital Profesional',
    descripcionCurso:
      'Técnicas de fotografía profesional, iluminación, composición y edición con Lightroom y Photoshop.',
    codigoCompleto: 'FOTO-PRO-2025-01',
    tipo: 'desempleados',
    modalidad: 'presencial',
    estado: 'abierta',
    fechaInicio: '2025-03-10',
    fechaFin: '2025-06-10',
    horario: 'Lunes a Viernes 09:00-14:00',
    duracionHoras: 200,
    precio: 0,
    plazasTotales: 12,
    plazasOcupadas: 8,
    porcentajeOcupacion: 67,
    profesorId: 'prof-7',
    profesorNombre: 'Patricia López Vega',
    profesorAvatar: undefined,
    sedeId: 'sede-santa-cruz',
    sedeNombre: 'CEP Santa Cruz',
    aulaId: 'aula-estudio',
    aulaNombre: 'Estudio Fotográfico',
    subvencionado: 'total',
    entidadesFinanciadoras: [
      {
        id: 'sepe',
        nombre: 'SEPE',
        logo: '/logos/sepe.png',
      },
    ],
  },
  {
    id: '8',
    plantillaId: 'curso-8',
    nombreCurso: 'SEO y Posicionamiento Web',
    descripcionCurso: 'Estrategias de SEO on-page, off-page, y análisis de keywords para ranking en Google.',
    codigoCompleto: 'SEO-WEB-2025-01',
    tipo: 'privados',
    modalidad: 'semipresencial',
    estado: 'abierta',
    fechaInicio: '2025-02-25',
    fechaFin: '2025-05-25',
    horario: 'Miércoles y Viernes 18:00-21:00',
    duracionHoras: 100,
    precio: 900,
    plazasTotales: 20,
    plazasOcupadas: 12,
    porcentajeOcupacion: 60,
    profesorId: 'prof-8',
    profesorNombre: 'Roberto Jiménez Cruz',
    profesorAvatar: undefined,
    sedeId: 'sede-sur',
    sedeNombre: 'CEP Sur',
    aulaId: 'aula-201',
    aulaNombre: 'Aula 201',
    subvencionado: 'no',
    entidadesFinanciadoras: [],
  },
]

// Statistics for course instances
export const instanciasStats = {
  total: instanciasData.length,
  abiertas: instanciasData.filter((i) => i.estado === 'abierta').length,
  planificadas: instanciasData.filter((i) => i.estado === 'planificada').length,
  enCurso: instanciasData.filter((i) => i.estado === 'en_curso').length,
  plazasTotales: instanciasData.reduce((acc, i) => acc + i.plazasTotales, 0),
  plazasOcupadas: instanciasData.reduce((acc, i) => acc + i.plazasOcupadas, 0),
  ocupacionPromedio: Math.round(
    instanciasData.reduce((acc, i) => acc + i.porcentajeOcupacion, 0) / instanciasData.length
  ),
}
