import { PlantillaCurso } from '@/types'

// Mock data for course templates (plantillas) - generic course information
export const plantillasCursosData: PlantillaCurso[] = [
  {
    id: 'plantilla-1',
    nombre: 'Marketing Digital Avanzado',
    descripcion:
      'Domina estrategias avanzadas de marketing digital, SEO, SEM, y análisis de métricas para impulsar tu negocio en el entorno digital actual.',
    imagenPortada: 'https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    area: 'Marketing Digital',
    tipo: 'privados',
    duracionReferencia: 200,
    precioReferencia: 1200,
    objetivos: [
      'Desarrollar estrategias de marketing digital efectivas',
      'Dominar herramientas de SEO y SEM',
      'Analizar métricas y KPIs para optimizar campañas',
      'Crear planes de contenido para redes sociales',
    ],
    contenidos: [
      'Fundamentos del marketing digital',
      'SEO técnico y de contenidos',
      'Campañas SEM con Google Ads',
      'Social Media Marketing',
      'Email Marketing y Automation',
      'Analítica web con Google Analytics',
    ],
    totalConvocatorias: 3,
    active: true,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2025-01-20T14:30:00Z',
  },
  {
    id: 'plantilla-2',
    nombre: 'Desarrollo Web Full Stack',
    descripcion:
      'Aprende a crear aplicaciones web completas desde el frontend hasta el backend con tecnologías modernas como React, Node.js y bases de datos.',
    imagenPortada: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=400&fit=crop',
    area: 'Desarrollo Web',
    tipo: 'ocupados',
    duracionReferencia: 300,
    precioReferencia: 0,
    objetivos: [
      'Desarrollar aplicaciones frontend con React',
      'Crear APIs RESTful con Node.js y Express',
      'Gestionar bases de datos relacionales y NoSQL',
      'Implementar autenticación y autorización',
      'Desplegar aplicaciones en la nube',
    ],
    contenidos: [
      'HTML5, CSS3 y JavaScript ES6+',
      'React y ecosistema moderno',
      'Node.js y Express para backend',
      'PostgreSQL y MongoDB',
      'APIs RESTful y GraphQL',
      'Docker y despliegue en AWS',
    ],
    totalConvocatorias: 2,
    active: true,
    created_at: '2024-02-01T09:00:00Z',
    updated_at: '2025-01-18T16:45:00Z',
  },
  {
    id: 'plantilla-3',
    nombre: 'Diseño Gráfico Profesional',
    descripcion:
      'Herramientas y técnicas de diseño gráfico profesional con Adobe Creative Suite y Figma para crear piezas visuales impactantes.',
    imagenPortada: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=400&fit=crop',
    area: 'Diseño Gráfico',
    tipo: 'desempleados',
    duracionReferencia: 250,
    precioReferencia: 0,
    objetivos: [
      'Dominar Adobe Photoshop, Illustrator e InDesign',
      'Crear identidades visuales de marca',
      'Diseñar piezas publicitarias efectivas',
      'Aplicar principios de diseño UX/UI',
    ],
    contenidos: [
      'Fundamentos del diseño gráfico',
      'Adobe Photoshop avanzado',
      'Adobe Illustrator para vectores',
      'InDesign para maquetación',
      'Figma para diseño UI',
      'Branding y diseño de identidad',
    ],
    totalConvocatorias: 2,
    active: true,
    created_at: '2024-01-20T11:30:00Z',
    updated_at: '2025-01-22T10:15:00Z',
  },
  {
    id: 'plantilla-4',
    nombre: 'Community Manager Profesional',
    descripcion:
      'Gestión profesional de redes sociales, creación de contenido y análisis de métricas para potenciar la presencia digital de marcas.',
    imagenPortada: 'https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    area: 'Marketing Digital',
    tipo: 'teleformacion',
    duracionReferencia: 150,
    precioReferencia: 800,
    objetivos: [
      'Gestionar múltiples plataformas de redes sociales',
      'Crear contenido visual y multimedia atractivo',
      'Diseñar estrategias de contenido efectivas',
      'Analizar métricas y optimizar rendimiento',
      'Gestionar crisis de reputación online',
    ],
    contenidos: [
      'Introducción al Social Media',
      'Facebook e Instagram para empresas',
      'LinkedIn para B2B',
      'TikTok y contenido viral',
      'Herramientas de gestión (Hootsuite, Buffer)',
      'Analítica de redes sociales',
    ],
    totalConvocatorias: 4,
    active: true,
    created_at: '2024-03-01T08:00:00Z',
    updated_at: '2025-01-25T12:00:00Z',
  },
  {
    id: 'plantilla-5',
    nombre: 'Producción Audiovisual',
    descripcion:
      'Técnicas de producción, edición y postproducción de contenido audiovisual profesional con herramientas de la industria.',
    imagenPortada: 'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?w=800&h=400&fit=crop',
    area: 'Audiovisual',
    tipo: 'privados',
    duracionReferencia: 220,
    precioReferencia: 1500,
    objetivos: [
      'Producir contenido audiovisual de calidad profesional',
      'Editar vídeo con Premiere Pro y DaVinci Resolve',
      'Crear motion graphics con After Effects',
      'Diseñar bandas sonoras y mezclar audio',
    ],
    contenidos: [
      'Fundamentos de la producción audiovisual',
      'Cámara y iluminación profesional',
      'Adobe Premiere Pro para edición',
      'DaVinci Resolve para color grading',
      'After Effects y motion graphics',
      'Diseño sonoro y post-audio',
    ],
    totalConvocatorias: 2,
    active: true,
    created_at: '2024-02-10T10:00:00Z',
    updated_at: '2025-01-19T15:30:00Z',
  },
  {
    id: 'plantilla-6',
    nombre: 'Excel Avanzado y Power BI',
    descripcion:
      'Análisis de datos y visualización con Excel avanzado y Power BI para la toma de decisiones empresariales basadas en datos.',
    imagenPortada: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=400&fit=crop',
    area: 'Gestión Empresarial',
    tipo: 'ocupados',
    duracionReferencia: 120,
    precioReferencia: 0,
    objetivos: [
      'Dominar funciones avanzadas de Excel',
      'Crear dashboards interactivos',
      'Analizar grandes volúmenes de datos',
      'Automatizar procesos con macros y Power Query',
      'Visualizar datos con Power BI',
    ],
    contenidos: [
      'Funciones avanzadas de Excel',
      'Tablas dinámicas y análisis de datos',
      'Power Query para ETL',
      'Macros y VBA básico',
      'Introducción a Power BI',
      'Creación de dashboards profesionales',
    ],
    totalConvocatorias: 3,
    active: true,
    created_at: '2024-01-25T09:30:00Z',
    updated_at: '2025-01-23T11:20:00Z',
  },
  {
    id: 'plantilla-7',
    nombre: 'SEO y Posicionamiento Web',
    descripcion:
      'Estrategias completas de SEO técnico, de contenidos y local para posicionar sitios web en los primeros resultados de búsqueda.',
    imagenPortada: 'https://images.pexels.com/photos/270637/pexels-photo-270637.jpeg?auto=compress&cs=tinysrgb&w=800&h=400&fit=crop',
    area: 'Marketing Digital',
    tipo: 'privados',
    duracionReferencia: 100,
    precioReferencia: 650,
    objetivos: [
      'Optimizar sitios web para motores de búsqueda',
      'Realizar auditorías SEO completas',
      'Desarrollar estrategias de link building',
      'Aplicar SEO local para negocios físicos',
    ],
    contenidos: [
      'Fundamentos de SEO',
      'SEO técnico (crawling, indexación)',
      'Keyword research y análisis de competencia',
      'SEO on-page y optimización de contenidos',
      'Link building y autoridad de dominio',
      'SEO local y Google My Business',
    ],
    totalConvocatorias: 2,
    active: true,
    created_at: '2024-03-05T14:00:00Z',
    updated_at: '2025-01-21T09:45:00Z',
  },
  {
    id: 'plantilla-8',
    nombre: 'Fotografía Digital Profesional',
    descripcion:
      'Técnicas de fotografía digital profesional, desde la captura hasta el retoque fotográfico avanzado con Lightroom y Photoshop.',
    imagenPortada: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&h=400&fit=crop',
    area: 'Audiovisual',
    tipo: 'privados',
    duracionReferencia: 180,
    precioReferencia: 950,
    objetivos: [
      'Dominar técnicas de fotografía digital',
      'Comprender iluminación natural y artificial',
      'Retocar fotografías de manera profesional',
      'Crear portafolio fotográfico',
    ],
    contenidos: [
      'Fundamentos de fotografía',
      'Composición y narrativa visual',
      'Iluminación para fotografía',
      'Fotografía de retrato y producto',
      'Adobe Lightroom para revelado',
      'Retoque avanzado con Photoshop',
    ],
    totalConvocatorias: 1,
    active: true,
    created_at: '2024-02-20T10:30:00Z',
    updated_at: '2025-01-24T13:15:00Z',
  },
]

export const plantillasStats = {
  total: plantillasCursosData.length,
  activas: plantillasCursosData.filter((p) => p.active).length,
  porArea: {
    marketing: plantillasCursosData.filter((p) => p.area === 'Marketing Digital').length,
    desarrollo: plantillasCursosData.filter((p) => p.area === 'Desarrollo Web').length,
    diseno: plantillasCursosData.filter((p) => p.area === 'Diseño Gráfico').length,
    audiovisual: plantillasCursosData.filter((p) => p.area === 'Audiovisual').length,
    gestion: plantillasCursosData.filter((p) => p.area === 'Gestión Empresarial').length,
  },
  totalConvocatorias: plantillasCursosData.reduce((acc, p) => acc + p.totalConvocatorias, 0),
}
