import { Student } from '@/types'

export const studentsData: Student[] = [
  {
    id: '1',
    first_name: 'María',
    last_name: 'González Ruiz',
    email: 'maria.gonzalez@email.com',
    phone: '+34 612 345 001',
    active: true,
    enrolled_courses: 2,
    completed_courses: 3,
  },
  {
    id: '2',
    first_name: 'Juan',
    last_name: 'Martínez López',
    email: 'juan.martinez@email.com',
    phone: '+34 612 345 002',
    active: true,
    enrolled_courses: 1,
    completed_courses: 1,
  },
  {
    id: '3',
    first_name: 'Ana',
    last_name: 'Rodríguez Sánchez',
    email: 'ana.rodriguez@email.com',
    phone: '+34 612 345 003',
    active: true,
    enrolled_courses: 3,
    completed_courses: 5,
  },
  {
    id: '4',
    first_name: 'Carlos',
    last_name: 'Fernández Torres',
    email: 'carlos.fernandez@email.com',
    phone: '+34 612 345 004',
    active: false,
    enrolled_courses: 0,
    completed_courses: 2,
  },
  {
    id: '5',
    first_name: 'Laura',
    last_name: 'García Pérez',
    email: 'laura.garcia@email.com',
    phone: '+34 612 345 005',
    active: true,
    enrolled_courses: 2,
    completed_courses: 4,
  },
  {
    id: '6',
    first_name: 'Pedro',
    last_name: 'López Martínez',
    email: 'pedro.lopez@email.com',
    phone: '+34 612 345 006',
    active: true,
    enrolled_courses: 1,
    completed_courses: 0,
  },
  {
    id: '7',
    first_name: 'Elena',
    last_name: 'Sánchez Ruiz',
    email: 'elena.sanchez@email.com',
    phone: '+34 612 345 007',
    active: true,
    enrolled_courses: 2,
    completed_courses: 6,
  },
  {
    id: '8',
    first_name: 'Miguel',
    last_name: 'Torres Díaz',
    email: 'miguel.torres@email.com',
    phone: '+34 612 345 008',
    active: true,
    enrolled_courses: 1,
    completed_courses: 2,
  },
]
