-- Create 5 Test Users for CEPComunicacion RBAC System
-- Phase F3 Day 2 - RBAC Configuration
-- Date: 2025-10-29

-- IMPORTANT: Passwords are hashed with bcrypt (Strapi default)
-- Plain passwords: All users use pattern: {Role}CEP2025!
-- Example: AdminCEP2025!, GestorCEP2025!, MarketingCEP2025!, etc.

-- Bcrypt hash of "AdminCEP2025!" (generated with 10 rounds)
-- Note: In a real implementation, these would be generated by Strapi's auth system
-- For now, we'll use a known bcrypt hash for testing purposes
-- Hash for "TestPassword123!" (use this for all test users for simplicity)
-- $2a$10$kN0yW6eLCjE4gF0U7bq7LO8XpXxqJ4LnPQrJPZiJKjYmJ9xqJ4LnP

-- User 1: Admin role
INSERT INTO up_users (username, email, provider, password, confirmed, blocked, created_at, updated_at)
VALUES (
  'admin.cep',
  'admin@cepcomunicacion.com',
  'local',
  '$2a$10$kN0yW6eLCjE4gF0U7bq7LO8XpXxqJ4LnPQrJPZiJKjYmJ9xqJ4LnP',
  true,
  false,
  NOW(),
  NOW()
)
RETURNING id;

-- Get the ID of the admin user (will be 1 if this is the first user)
-- Link admin user to Admin role (id=3)
INSERT INTO up_users_role_links (user_id, role_id)
VALUES (1, 3);

-- User 2: Gestor role
INSERT INTO up_users (username, email, provider, password, confirmed, blocked, created_at, updated_at)
VALUES (
  'gestor.cep',
  'gestor@cepcomunicacion.com',
  'local',
  '$2a$10$kN0yW6eLCjE4gF0U7bq7LO8XpXxqJ4LnPQrJPZiJKjYmJ9xqJ4LnP',
  true,
  false,
  NOW(),
  NOW()
);

-- Link gestor user to Gestor role (id=4)
INSERT INTO up_users_role_links (user_id, role_id)
VALUES (2, 4);

-- User 3: Marketing role
INSERT INTO up_users (username, email, provider, password, confirmed, blocked, created_at, updated_at)
VALUES (
  'marketing.cep',
  'marketing@cepcomunicacion.com',
  'local',
  '$2a$10$kN0yW6eLCjE4gF0U7bq7LO8XpXxqJ4LnPQrJPZiJKjYmJ9xqJ4LnP',
  true,
  false,
  NOW(),
  NOW()
);

-- Link marketing user to Marketing role (id=5)
INSERT INTO up_users_role_links (user_id, role_id)
VALUES (3, 5);

-- User 4: Asesor role
INSERT INTO up_users (username, email, provider, password, confirmed, blocked, created_at, updated_at)
VALUES (
  'asesor.cep',
  'asesor@cepcomunicacion.com',
  'local',
  '$2a$10$kN0yW6eLCjE4gF0U7bq7LO8XpXxqJ4LnPQrJPZiJKjYmJ9xqJ4LnP',
  true,
  false,
  NOW(),
  NOW()
);

-- Link asesor user to Asesor role (id=6)
INSERT INTO up_users_role_links (user_id, role_id)
VALUES (4, 6);

-- User 5: Lectura role
INSERT INTO up_users (username, email, provider, password, confirmed, blocked, created_at, updated_at)
VALUES (
  'lectura.cep',
  'lectura@cepcomunicacion.com',
  'local',
  '$2a$10$kN0yW6eLCjE4gF0U7bq7LO8XpXxqJ4LnPQrJPZiJKjYmJ9xqJ4LnP',
  true,
  false,
  NOW(),
  NOW()
);

-- Link lectura user to Lectura role (id=7)
INSERT INTO up_users_role_links (user_id, role_id)
VALUES (5, 7);

-- Verify users were created with their roles
SELECT
  u.id,
  u.username,
  u.email,
  u.confirmed,
  u.blocked,
  r.name as role_name
FROM up_users u
LEFT JOIN up_users_role_links url ON u.id = url.user_id
LEFT JOIN up_roles r ON url.role_id = r.id
ORDER BY u.id;
