# Blackbox Exporter Configuration for CEPComunicacion v2
# HTTP, HTTPS, TCP, ICMP probing

modules:
  # HTTP 2xx probe - check if endpoint returns success
  http_2xx:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 201, 202, 204]
      method: GET
      preferred_ip_protocol: "ip4"
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: false

  # HTTP POST probe - for API endpoints
  http_post_2xx:
    prober: http
    timeout: 10s
    http:
      method: POST
      headers:
        Content-Type: application/json
      body: '{}'
      valid_status_codes: [200, 201, 202]

  # HTTPS probe with SSL verification
  https_2xx:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 201, 202, 204]
      method: GET
      preferred_ip_protocol: "ip4"
      follow_redirects: true
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false

  # TCP connect probe
  tcp_connect:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"

  # ICMP ping probe
  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"

  # DNS probe
  dns_mx:
    prober: dns
    timeout: 5s
    dns:
      query_name: "cepcomunicacion.com"
      query_type: "MX"

  # PostgreSQL TCP probe
  postgres_tcp:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - expect: "^\\x00"
      tls: false

  # Redis TCP probe
  redis_tcp:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - send: "PING\r\n"
        - expect: "^\\+PONG"
